#!/bin/sh
#----
# Launcher script to select a command to run, history of the run commands
# will be kept on a history file.
#
# Requires fzf, and either stest (from dmenu package) or just the find tool.
#----

HISTORY=${XDG_STATE_HOME:-"$HOME/.local/state"}/dmenu_run.history

printf "\033]0;Select/Type command to execute\007"
cmd=$(
	IFS=:
	if hash stest 2>&-
	then
		stest -flx $PATH
	elif hash find 2>&-
	then
		find $PATH -maxdepth 1 -type f -executable 2>&- | sed 's/.*\///'
	fi | {
		sort -u | cat "$HISTORY" - | fzf --tiebreak=begin "$@"
	}
)

# Launch command in the background, using preferred shell
${DMENU_LAUNCHER:-${SHELL:-"/bin/sh"} -c} "$cmd" &

# Update history file
if [ "$cmd" ] && hash ${cmd%% *}
then
	{ echo ${cmd} && grep -v "^${cmd}$" "$HISTORY"; } >"${HISTORY}~"
	mv "${HISTORY}~" "$HISTORY"
fi

