#
# i3status-rust configuration
#
# See https://greshake.github.io/i3status-rust/i3status_rs/blocks/index.html

[theme]
theme = "solarized-dark"
#[theme.overrides]
#critical.bg = "#ff0000"
#critical.fg = "#ffffff"


[icons]
icons = "material-nf" # for icons see: https://www.nerdfonts.com/cheat-sheet
[icons.overrides]
thermometer = " 🌡 "

# ---------------

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(w:60)|                             "
[block.theme_overrides]
idle_bg = "#001010"
[[block.click]]
button = "down"
cmd = "swaymsg focus next"
[[block.click]]
button = "up"
cmd = "swaymsg focus prev"
[[block.click]]
button = "left"
cmd = "swaymsg layout toggle tabbed splith splitv"
[[block.click]]
button = "right"
cmd = "swaymsg floating toggle"

[[block]]
block = "notify"


[[block]]
block = "hueshift"
if_command = "hash wlsunset"
hue_shifter = "wlsunset"
step = 100
click_temp = 3500

[[block]]
block = "custom" # System upgrade script
interval = 3600
command = "$swaydir/sysupgrade.sh show"
json = true
signal = 4 # update with: pkill -SIGRTMIN+4 i3status-rs
[[block.click]]
button = "left"
cmd = "$XTERM -e sh -c '${swaydir:-.}/sysupgrade.sh; sleep 20'"

[[block]]
block = "pacman"
interval = 3600
format = "$icon$pacman+$aur"
format_singular = "$icon$both"
critical_updates_regex = "(linux |linux-lts|linux-zen)"
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "paru -Qua"
[[block.click]]
button = "left"
cmd = "$XTERM -e sh -c '${swaydir:-.}/sysupgrade.sh; sleep 20'"


[[block]]
block = "temperature"
format = "$icon$average〰$max"
good = 59
idle = 79
info = 84
warning = 89

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available "
format_alt = " $icon $available/$total ($percentage) "

[[block]]
block = "memory"
interval = 5

[[block]]
block = "cpu"
interval = 5
format = "$icon $barchart $utilization"
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "load"
interval = 1
info = 0.6
warning = 0.75
critical = 0.9
format = "$icon$1m $5m"
[[block.click]]
button = "left"
cmd = "$XTERM -e btop"


[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|$ip} "
[[block.click]]
button = "left"
cmd = "$XTERM -e nmtui"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "$XTERM -e sh -c 'pulsemixer'"


[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%a %d/%m %R') "
[[block.click]]
button = "left"
cmd = "$XTERM -e sh -c 'cal -3'"



