


# WASD navigation
bind = SUPER, W, exec, "${XDG_CONFIG_HOME:-$HOME/.config}/hypr/cyclewindows.sh" next
bind = SUPER, S, exec, "${XDG_CONFIG_HOME:-$HOME/.config}/hypr/cyclewindows.sh" prev
bindd = SUPER, D, Next workspace, workspace, m+1
bindd = SUPER, A, Previous workspace, workspace, m-1

bindd = SUPER SHIFT, C, Close active window, killactive,

# App launcher
bind = SUPER, E, exec, xdg-terminal-exec --app-id=dialog fzmenu-run

# Terminal
bindd = SUPER, RETURN, Terminal, exec, xdg-terminal-exec --dir="$HOME"

# 
bind = SUPER, XF86Display, exec, xdg-terminal-exec --app-id=dialog --hold hyprctl activewindow -j



# Toggle groups
bindd = SUPER, G, Toggle window grouping, togglegroup
bindd = SUPER ALT, G, Move active window out of group, moveoutofgroup


# Switch workspaces with SUPER + [1-9; 0]
bindd = SUPER, code:10, Switch to workspace 1, workspace, 1
bindd = SUPER, code:11, Switch to workspace 2, workspace, 2
bindd = SUPER, code:12, Switch to workspace 3, workspace, 3
bindd = SUPER, code:13, Switch to workspace 4, workspace, 4
bindd = SUPER, code:14, Switch to workspace 5, workspace, 5
bindd = SUPER, code:15, Switch to workspace 6, workspace, 6
bindd = SUPER, code:16, Switch to workspace 7, workspace, 7
bindd = SUPER, code:17, Switch to workspace 8, workspace, 8
bindd = SUPER, code:18, Switch to workspace 9, workspace, 9
bindd = SUPER, code:19, Switch to workspace 10, workspace, 10


# Move active window to a workspace with SUPER + SHIFT + [1-9; 
bindd = SUPER SHIFT, code:10, Move window to workspace 1, movetoworkspace, 1
bindd = SUPER SHIFT, code:11, Move window to workspace 2, movetoworkspace, 2
bindd = SUPER SHIFT, code:12, Move window to workspace 3, movetoworkspace, 3
bindd = SUPER SHIFT, code:13, Move window to workspace 4, movetoworkspace, 4
bindd = SUPER SHIFT, code:14, Move window to workspace 5, movetoworkspace, 5
bindd = SUPER SHIFT, code:15, Move window to workspace 6, movetoworkspace, 6
bindd = SUPER SHIFT, code:16, Move window to workspace 7, movetoworkspace, 7
bindd = SUPER SHIFT, code:17, Move window to workspace 8, movetoworkspace, 8
bindd = SUPER SHIFT, code:18, Move window to workspace 9, movetoworkspace, 9
bindd = SUPER SHIFT, code:19, Move window to workspace 10, movetoworkspace, 10


# Move/resize windows with mainMod + LMB/RMB and dragging
bindmd = SUPER, mouse:272, Move window, movewindow
bindmd = SUPER, mouse:273, Resize window, resizewindow

