# Application bindings
bindd = SUPER SHIFT, F, File manager, exec, nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, browser
#bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
#bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
#bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
#bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
#bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
#bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://app.hey.com/calendar/weeks/"
#bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://app.hey.com"
#bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
#bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"





