# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Source all hyprland conf files in the ~/.config/hypr folder
# format of the files would be "<nn>_<name>.conf" with <nn> being the number for the load order
source = ./??_*.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu

plugin {
    hyprscrolling {
        column_width = 1
        #fullscreen_on_one_column = false
    }
}


general {
    #layout = master
#    layout = scrolling  # Options: dwindle, master
}


group {
    groupbar {
        # Font settings
        font_size = 10
        height = 7          # Total height of the bar (adjust to fit your font)
        
        # Remove "padding" by making the bar height barely larger than the font
        # and setting gradients to 0 if desired
        render_titles = true
        #gradients = false
        
        # Color the bar to match your aesthetic
        col.active = rgba(00a08088)
        col.inactive = rgba(59595988)
        
        # Text alignment (center usually looks best for tiny bars)
        text_color = rgba(ffffffff)
    }
}

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This rule targets windows that are part of a group
#windowrule = borderwidth 0, grouped:1
windowrule = float on, match:class dialog
windowrule = group set, match:class one.ablaze.floorp
windowrule = group set, match:class floorp


